pipeline:
  type: Ingest

  location_id: "morro"
  dataset_name: "buoy_z06"
  qualifier: "lidar"
  temporal: "10min"
  data_level: "a1"

dataset_definition:  # Describes the dataset that will be produced
  attributes:
    title: Lidar Ingest for .sta file
    description: Example ingest of data from a buoy stationed at Morro Bay, California.
    conventions: "ME Data Pipeline Standards: Version 1.0"
    institution: Pacific Northwest National Laboratory
    code_url: https://github.com/tsdat/tsdat/releases/tag/v0.2.2
    location_meaning: Morro Bay

  dimensions:
    time:
        length: unlimited
    
    height:
        length: 12

  variables:

    time:
      input:
        name: Timestamp (end of interval)
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%Y/%m/%d %H:%M"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    height:
      data: [40, 60, 80, 90, 100, 120, 140, 160, 180, 200, 220, 240]
      dims: [height]
      type: int
      attrs:
        long_name: Height ASL
        units: m
    
    wind_speed:
      dims: [time, height]
      type: float
      attrs:
        long_name: Wind Speed
        units: m/s
      
    wind_direction:
      dims: [time, height]
      type: float
      attrs:
        long_name: Wind Direction
        units: degrees
    
    data_availability:
      dims: [time, height]
      type: float
      attrs:
        long_name: Availability
        units: "%"

    pressure:
      input: 
        name: Pressure (hPa)
        units: hPa
      dims: [time]
      type: float
      attrs:
        long_name: Pressure
        units: hPa

#-----------------------------------------------------------------
quality_management:

  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
