pipeline:
  type: Ingest

  location_id: "morro"
  dataset_name: "buoy_z06"
  qualifier: "waves"
  temporal: "20min"
  data_level: "a1"


dataset_definition:  # Describes the dataset that will be produced
  attributes:
    title: Waves Buoy Dataset
    description: "Pacific Northwest National Laboratory (PNNL) manages two 
    AXYS WindSentinelTM buoys (Buoys #120 and #130) on behalf of the U.S. 
    Department of Energy (DOE) that collect a comprehensive set of 
    meteorological and oceanographic (metocean) data to support resource 
    characterization for wind energy offshore. The buoys have been deployed 
    off the California coast in partnership with the Bureau of Ocean Energy 
    Management (BOEM) from September 2020 through October 2021"
    doi: 10.21947/1671051
    conventions: "ME Data Pipeline Standards: Version 1.0"
    institution: Pacific Northwest National Laboratory
    code_url: https://github.com/tsdat/tsdat/releases/tag/v0.2.2
    location_meaning: Morro Bay
    instrument_name: WindSentinel
    instrument_meaning: Self-powered floating buoy hosting a suite of meteorological and marine instruments.
    instrument_manufacturer: AXYS Technologies Inc.
    sampling_interval: 20 min

  dimensions:
    time:
        length: unlimited

  variables:

    time:
      input:
        # Name of the variable in the raw data
        name: DataTimeStamp
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%Y-%m-%d %H:%M:%S"
      dims: [time]
      type: long
      attrs:
        long_name: Time offset from epoch
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    wave_type:  
      input: # From waves csv
        name: WaveType
        units: "1"
      dims: [time]
      type: double
      attrs:
        long_name: Wave Type
        units: "1"
        comment: "User-programmable classification of different wave types. Wave types are not defined for this deployment"
        _FillValue: -9999

    num_zero_crossings:  
      input: # From waves csv
        name: ZCN
        units: "1"
      dims: [time]
      type: int
      attrs:
        long_name: Number of Zero Crossings
        units: "1"
        _FillValue: -9999

    mean_wave_height:  
      input: # From waves csv
        name: Havg
        units: m
      dims: [time]
      type: double
      attrs:
        long_name: Average Wave Height
        comment: Wave height, average calculated from timeseries
        units: m
        valid_delta: 0.03
        valid_range: [0, 10]
        _FillValue: -9999

    mean_wave_period_ts:  
      input: # From waves csv
        name: Tavg
        units: s
      dims: [time]
      type: double
      attrs:
        long_name: Average Wave Period
        comment: Wave period, average caculated from timeseries
        units: s
        valid_delta: 0.03
        valid_range: [0, 30]
        _FillValue: -9999

    mean_wave_period:  
      input: # From waves csv
        name: MeanPeriod
        units: s
      dims: [time]
      type: double
      attrs:
        long_name: Mean Wave Period from Spectral Moments
        comment: Wave period, average calculated from the zeroth and first spectral moments
        units: s
        valid_delta: 5
        valid_range: [0, 30]
        _FillValue: -9999

    mean_wave_direction:  
      input: # From waves csv
        name: MeanDirection
        units: degrees
      dims: [time]
      type: double
      attrs:
        long_name: Mean Wave Direction
        units: degrees
        valid_delta: 15
        valid_range: [0, 360]
        _FillValue: -9999

    mean_wave_spread:  
      input: # From waves csv
        name: MeanSpread
        units: degrees
      dims: [time]
      type: double
      attrs:
        long_name: Mean Wave Spread
        units: degrees
        valid_delta: 15
        valid_range: [0, 360]
        _FillValue: -9999

    max_wave_height:  
      input: # From waves csv
        name: Hmax
        units: m
      dims: [time]
      type: double
      attrs:
        long_name: Maximum Wave Height
        units: m
        valid_delta: 0.03
        valid_range: [0, 10]
        _FillValue: -9999

    max_wave_period:  
      input: # From waves csv
        name: Tmax
        units: s
      dims: [time]
      type: double
      attrs:
        long_name: Maximum Wave Period
        units: s
        valid_delta: 0.03
        valid_range: [0, 30]
        _FillValue: -9999

    significant_wave_height_ts:  
      input: # From waves csv
        name: Hsig
        units: m
      dims: [time]
      type: double
      attrs:
        long_name: Significant Wave Height
        comment: Wave height, significant, average of highest 1/3rd of waves, calculated from timeseries.
        units: m
        valid_delta: 0.03
        valid_range: [0, 10]
        _FillValue: -9999

    significant_wave_period:  
      input: # From waves csv
        name: Tsig
        units: s
      dims: [time]
      type: double
      attrs:
        long_name: Significant Wave Period
        comment: Wave period, significant, average of highest 1/3rd of waves, calculated from timeseries
        units: s
        valid_delta: 0.03
        valid_range: [0, 30]
        _FillValue: -9999

    significant_10_wave_height:  
      input: # From waves csv
        name: H110
        units: m
      dims: [time]
      type: double
      attrs:
        long_name: Significant Wave Height
        comment: Wave height, significant, average of highest 1/10th of waves.
        units: m
        valid_delta: 0.03
        valid_range: [0, 10]
        _FillValue: -9999

    significant_10_wave_period:  
      input: # From waves csv
        name: T110
        units: s
      dims: [time]
      type: double
      attrs:
        long_name: Significant Wave Period
        comment: Wave period, significant, average of highest 1/10th of waves.
        units: s
        valid_delta: 0.03
        valid_range: [0, 30]
        _FillValue: -9999

    max_crest_period:
      input: # From waves csv
        name: MaxCrest
        units: m
      dims: [time]
      type: double
      attrs:
        long_name: Max Crest Period
        comment: Wave period between highest wave crests
        units: m
        valid_delta: 1
        valid_range: [0, 30]
        _FillValue: -9999

    peak_wave_period:  
      input: # From waves csv
        name: PeakPeriod
        units: s
      dims: [time]
      type: double
      attrs:
        long_name: Peak wave period
        comment: Wave period associated with maximum energy found in wave elevation spectrum
        units: s
        valid_delta: 10
        valid_range: [0, 30]
        _FillValue: -9999

    peak_wave_direction:  
      input: # From waves csv
        name: PeakDirection
        units: degrees
      dims: [time]
      type: double
      attrs:
        long_name: Peak Wave Direction
        comment: Wave direction corresponding to peak wave period
        units: degrees
        valid_delta: 15
        valid_range: [0, 360]
        _FillValue: -9999

    peak_wave_spread:  
      input: # From waves csv
        name: PeakSpread
        units: degrees
      dims: [time]
      type: double
      attrs:
        long_name: Peak Wave Spread
        comment: Wave spread corresponding to peak wave period
        units: degrees
        valid_delta: 15
        valid_range: [0, 360]
        _FillValue: -9999

    peak_wave_period_read:  
      input: # From waves csv
        name: TP5
        units: s
      dims: [time]
      type: double
      attrs:
        long_name: Peak Wave Period (Read)
        comment: Peak wave period computed by the Read method
        units: s
        valid_delta: 5
        valid_range: [0, 30]
        _FillValue: -9999

    significant_wave_height:  
      input: # From waves csv
        name: HM0
        units: m
      dims: [time]
      type: double
      attrs:
        long_name: Significant Wave Height
        comment: Significant wave height, calculated from the zeroth spectral moment
        units: m
        valid_delta: 3
        valid_range: [0, 30]
        _FillValue: -9999

    wave_energy_period:  
      input: # From waves csv
        name: Te
        units: s
      dims: [time]
      type: double
      attrs:
        long_name: Wave Energy Period
        comment: Wave energy period, calculated from the negative first and zeroth spectral moments
        units: s
        valid_delta: 10
        valid_range: [0, 30]
        _FillValue: -9999

    wave_duration:  
      input: # From waves csv
        name: DurationMs
        units: s
      dims: [time]
      type: double
      attrs:
        long_name: Wave Duration
        units: s
        valid_delta: 100
        valid_range: [0, 60000]
        _FillValue: -9999

    F1:  
      input: # From waves csv
        name: F1
        units: "1"
      dims: [time]
      type: double
      attrs:
        long_name: F1
        units: "1"
        _FillValue: -9999

    F2:  
      input: # From waves csv
        name: F1
        units: "1"
      dims: [time]
      type: double
      attrs:
        long_name: F1
        units: "1"
        _FillValue: -9999

#-----------------------------------------------------------------
quality_management:

  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS
  
  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS

  manage_fail_min:
    checker:
      classname: tsdat.qc.checkers.CheckFailMin
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 2
          assessment: Bad
          meaning: "Value is less than the fail_range."
    variables:
      - DATA_VARS

  manage_fail_max:
    checker:
      classname: tsdat.qc.checkers.CheckFailMax
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 3
          assessment: Bad
          meaning: "Value is greater than the fail_range."
    variables:
      - DATA_VARS

  manage_warn_min:
    checker:
      classname: tsdat.qc.checkers.CheckWarnMin
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 4
          assessment: Indeterminate
          meaning: "Value is less than the warn_range."
    variables:
      - DATA_VARS

  manage_warn_max:
    checker:
      classname: tsdat.qc.checkers.CheckWarnMax
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 5
          assessment: Indeterminate
          meaning: "Value is greater than the warn_range."
    variables:
      - DATA_VARS

  manage_valid_delta:
    checker:
      classname: tsdat.qc.checkers.CheckValidDelta
      parameters:
        dim: time
    handlers:
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 6
          assessment: Indeterminate
          meaning: "Difference between current and previous values exceeds valid_delta."
    variables:
      - DATA_VARS
